### ISSUE TITLE
FIM recursive wildcard not behaving as expected

### ISSUE THREAD

**Issue by tstallings** [facebook/osquery#1142]
I have the following file paths in my config from FIM

    "/Users/%/Applications/%",
    "/Users/%/Library/LaunchAgents/%"

I understand that these probably fall into the gotcha's of the current wildcarding rules as stated on the [read the docs](http://osquery.readthedocs.org/en/latest/development/wildcard-rules/) rules on wildcarding because I'm getting FIM events for paths that look like 

    /Users/tommy.stallings/Library/Application Support/Google/Chrome/Default/Cookies-journal

Can we push this issue to be fixed sooner rather than later because it makes it impossible to write a standardized config to deploy to multiple end points. The only solution I have found is to add the user name to the path like so

    "/Users/tommy.stallings/Library/LaunchAgents/%"

which makes a standard deploy very difficult.

**Comment by marpaia** [comment]
So, you're saying that `/Users/%/Applications/%` matches `/Users/tommy.stallings/Library/Application Support/Google/Chrome/Default/Cookies-journal`? I don't think that should happen, so that's a bug if true, IMO. 

What's the problem that you've seen with `/Users/%/Library/LaunchAgents/%` though? What does `/Users/tommy.stallings/` return that `/Users/%/` doesn't?

**Comment by tstallings** [comment]
Ok, I figured out what the actual problem was. It is actually being caused by 

    "/Users/%/"

This should only be matching file and directory events in `/Users/<user>/`, not recursively in all sub directories.

**Comment by tstallings** [comment]
Here's my current config running with osquery version `osquery 1.4.5-41-g5b43067`
```
{
    "options": {
        "host_identifier": "uuid",
        "database_path": "/var/osquery/osquery.db", 
        "event_pubsub_expiry": "86000", 
        "worker_threads": "4", 
        "schedule_splay_percent": "10", 
        "log_result_events": "true", 
        "config_plugin": "filesystem", 
        "debug": "false", 
        "verbose_debug": "false", 
        "pidfile": "/var/osquery/osquery.pidfile", 
        "logger_plugin": "filesystem",
        "logger_path": "/var/log/osquery"
    },
    "schedule": {
        "fim" : {
            "query": "select target_path, category, time, action from file_events;", 
            "interval": 60
        }
    },
    "file_paths": {
        "Users": [
            "/Users/%/"
        ]
    }
}
```

And query results of that config
```
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:56:55 2015 UTC","unixTime":"1431575815","columns":{"action":"ATTRIBUTES_MODIFIED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Saved Application State\/com.apple.Terminal.savedState\/windows.plist","time":"1431575781"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:56:55 2015 UTC","unixTime":"1431575815","columns":{"action":"ATTRIBUTES_MODIFIED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Saved Application State\/com.apple.Terminal.savedState\/window_5.data","time":"1431575781"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:56:55 2015 UTC","unixTime":"1431575815","columns":{"action":"UPDATED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Application Support\/Google\/Chrome\/Default\/Cookies-journal","time":"1431575803"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:57:50 2015 UTC","unixTime":"1431575870","columns":{"action":"ATTRIBUTES_MODIFIED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Google\/GoogleSoftwareUpdate\/Servers","time":"1431575827"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:57:50 2015 UTC","unixTime":"1431575870","columns":{"action":"ATTRIBUTES_MODIFIED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Google","time":"1431575827"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:57:50 2015 UTC","unixTime":"1431575870","columns":{"action":"ATTRIBUTES_MODIFIED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Google\/GoogleSoftwareUpdate","time":"1431575827"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:57:50 2015 UTC","unixTime":"1431575870","columns":{"action":"ATTRIBUTES_MODIFIED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Google\/GoogleSoftwareUpdate\/TicketStore","time":"1431575827"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:57:50 2015 UTC","unixTime":"1431575870","columns":{"action":"ATTRIBUTES_MODIFIED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Google\/GoogleSoftwareUpdate\/TicketStore\/Keystone.ticketstore","time":"1431575827"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:57:50 2015 UTC","unixTime":"1431575870","columns":{"action":"UPDATED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Application Support\/Google\/Chrome\/Default\/Cookies-journal","time":"1431575855"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:57:50 2015 UTC","unixTime":"1431575870","columns":{"action":"CREATED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Preferences\/.GlobalPreferences.plist.6030n3X","time":"1431575859"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:57:50 2015 UTC","unixTime":"1431575870","columns":{"action":"MOVED_TO","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/Preferences\/.GlobalPreferences.plist","time":"1431575859"},"action":"added"}
{"name":"fim","hostIdentifier":"E65715D0-086B-5FA8-AB6E-5F269F5B6A0D","calendarTime":"Thu May 14 03:57:50 2015 UTC","unixTime":"1431575870","columns":{"action":"DELETED","category":"Users","target_path":"\/Users\/tommy.stallings\/Library\/LaunchAgents\/test","time":"1431575864"},"action":"added"}
```

**Comment by theopolis** [comment]
Good catch! I *think* this issue was brought up before. IIRC the globbing code we have is applied to your `file_paths` selection then a FSEvents watcher is created for each matching dir/file. BUT FSEvents as we have the publisher written will return all events as if your original subscription was meant "recursive". The only way to filter was to re-apply the globbing on each event and only emit the matches. That re-glob was expensive to say the least. 

The solution, again, based on the above assumption-- is to tailor our FSEventsEventPublisher code to NOT act recursively. If that's at all possible given the FSEvents eventing API.

**Comment by theopolis** [comment]
Hey @tstallings, sorry this took so long to get attention. :( 

Would you mind giving the master build a try and see if #1266 and https://github.com/facebook/osquery/commit/7aac5fd3583c918f24fc36887861517bb67a69d5#diff-2661bc42fb63e963aa43eeddaeec6a96R207 make OS X / FSEvents work as expected?

**Comment by tstallings** [comment]
Will do. No worries about the time.

**Comment by tstallings** [comment]
Doesn't look like it's working. Using the same config I posted above, I'm not getting any events now. Should I try your fork?

**Comment by theopolis** [comment]
Oh, right, if you don't mind:

```
~git/osquery/$ git remote add theopolis https://github.com/theopolis/osquery
~git/osquery/$ git fetch theopolis
~git/osquery/$ git checkout event_streams
```

There's still 1 remaining issue and that's with patterns like: `/Users/%/Applications/%%`.

But:
```
/Users/%/
/Users/%/Applications/%
```

should be working!

**Comment by tstallings** [comment]
Still not getting anything in the `file_events` table. 

    I0706 15:31:33.706461 2003682048 config.cpp:129] Verbose logging enabled by config option
    I0706 15:31:33.706665 2003682048 config.cpp:129] Verbose logging enabled by config option
    I0706 15:31:33.706796 2003682048 file_events.cpp:58] Added listener to: /Users/*/
    I0706 15:31:33.706882 230834176 events.cpp:502] Starting event publisher run loop: diskarbitration
    I0706 15:31:33.706898 231370752 events.cpp:502] Starting event publisher run loop: fsevents
    I0706 15:31:33.706907 231907328 events.cpp:502] Starting event publisher run loop: iokit_hid
    I0706 15:31:33.706919 232443904 events.cpp:502] Starting event publisher run loop: scnetwork
    osquery - being built, with love, at Facebook
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Using a virtual database. Need help, type '.help'
    osquery> .schema file_events
    CREATE TABLE file_events(target_path TEXT, category TEXT, action TEXT, transaction_id BIGINT, md5 TEXT, sha1 TEXT, sha256 TEXT, time BIGINT);

    osquery> select * from file_events; //Check to make sure nothing is there
    I0706 15:33:00.353013 2003682048 db_handle.cpp:116] Opening RocksDB handle: /var/osquery/osquery.db
    osquery> select * from file_events; //created file /Users/test
    osquery> select * from file_events; //deleted file /Users/test


Am I missing something? I did get a new system a few weeks ago, but I also did `make deps` so everything should be there.

**Comment by marpaia** [comment]
@tstallings just for completeness, after you switched to the `event_streams` branch, you re-built the binary, right?

**Comment by tstallings** [comment]
and installed it ;)

**Comment by theopolis** [comment]
Right, I'm still working through documentation changes in that PR, but essentially:

- `/Users/%/Applications` -> I'd like to monitor changes to the Application directory itself!
- `/Users/%/Applications/` -> Same.
- `/Users/%/Applications/%` -> I'd like all events on file+folders one-level deep into Applications.
- `/Users/%/Applications/%%` -> I'd like ALL the events within each user's `~/Application` folder!!!
- ~~`/Users/%%/Applications/%`~~ -> This doesn't really make sense, we could twist it an **try** to assume what someone means, but better to just not support inline recursive operators.

@tstallings we were not getting events for `/Users/%/`, because it should now need a final `%`. But I will ping back when there are tests and documentation in the PR for each use case above. :)

**Comment by tstallings** [comment]
A final `%` seems a bit counter-intuitive doesn't it. What I'm going for is I want to know if there is a new file or folder in `/Users/` (as in, a new user was created on the system and now has a `/Users/<user>` folder). Would I just need `/Users/` in that case?

**Comment by marpaia** [comment]
@tstallings you should just schedule `select * from users;` if that's your underlying motivation. that way you'll get users that don't have home directories in `/Users` as well.

**Comment by tstallings** [comment]
It's not my only motivation. Just one of them as an example. I do use `select * from users;` as well.

**Comment by theopolis** [comment]
Ok so how about:

- `/Users/%/Applications` -> I'd like to monitor changes to the Application directory itself!
- `/Users/%/Applications/` -> I'd like events on files+folders within Applications (one level deep).
- `/Users/%/Applications/%` -> Same.
- `/Users/%/Applications/%%` -> I'd like ALL the events within each user's `~/Application` folder!!!
- ~~`/Users/%%/Applications/%`~~ -> This doesn't really make sense, we could twist it an **try** to assume what someone means, but better to just not support inline recursive operators.

So if you only include: `/Users/%/Applications/` in your list you should expect the following behavior:
```
[reed@reed-mbp] ~/git/github/osquery/build/testing(branch:event_streams) » ../debug_darwin/osquery/osqueryi --config_path ./osquery.conf --verbose --events_expiry=1
I0707 00:15:17.880369 1926947584 init.cpp:197] osquery initialized [version=1.4.7-47-g2dfe312]
I0707 00:15:17.880599 1926947584 extensions.cpp:178] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I0707 00:15:17.880749 1926947584 db_handle.cpp:116] Opening RocksDB handle: /Users/reed/.osquery/shell.db
I0707 00:15:17.886409 1926947584 config.cpp:71] Updating config with source: ./osquery.conf
I0707 00:15:17.887650 1926947584 file_events.cpp:58] Added listener to: /Users/*/Applications/
I0707 00:15:17.889683 39104512 interface.cpp:220] Extension manager service starting: /Users/reed/.osquery/shell.em
I0707 00:15:17.889823 39641088 events.cpp:502] Starting event publisher run loop: diskarbitration
I0707 00:15:17.890046 40177664 events.cpp:502] Starting event publisher run loop: fsevents
I0707 00:15:17.890905 40714240 events.cpp:502] Starting event publisher run loop: iokit_hid
I0707 00:15:17.890931 41250816 events.cpp:502] Starting event publisher run loop: scnetwork
osquery - being built, with love, at Facebook
Using a virtual database. Need help, type '.help'
osquery> select * from file_events;
I0707 00:15:20.095867 1926947584 db_handle.cpp:116] Opening RocksDB handle: /Users/reed/.osquery/shell.db
osquery> 
[1]  + 30375 suspended  ../debug_darwin/osquery/osqueryi --config_path ./osquery.conf --verbose 
------------------------------------------------------------
[reed@reed-mbp] ~/git/github/osquery/build/testing(branch:event_streams) » mkdir ~/Applications/NewApp.app
------------------------------------------------------------
[reed@reed-mbp] ~/git/github/osquery/build/testing(branch:event_streams) » touch ~/Applications/NewApp2.app
------------------------------------------------------------
[reed@reed-mbp] ~/git/github/osquery/build/testing(branch:event_streams) » touch ~/Applications
------------------------------------------------------------
[reed@reed-mbp] ~/git/github/osquery/build/testing(branch:event_streams) » mkdir ~/Applications/NewApp.app/Contents
------------------------------------------------------------
[reed@reed-mbp] ~/git/github/osquery/build/testing(branch:event_streams) » fg
[1]  + 30375 continued  ../debug_darwin/osquery/osqueryi --config_path ./osquery.conf --verbose 
osquery> select * from file_events;
+--------------------------------------+----------+---------+----------------+----------------------------------+------------------------------------------+------------------------------------------------------------------+------------+
| target_path                          | category | action  | transaction_id | md5                              | sha1                                     | sha256                                                           | time       |
+--------------------------------------+----------+---------+----------------+----------------------------------+------------------------------------------+------------------------------------------------------------------+------------+
| /Users/reed/Applications/NewApp.app  | tmp      | CREATED | 14304774       | d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 | 1436253350 |
| /Users/reed/Applications/NewApp2.app | tmp      | CREATED | 14304886       | d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 | 1436253350 |
+----------
```

Let me know if this seems ok! :smile_cat:

**Comment by theopolis** [comment]
Hey @tstallings, if you have a chance, do you mind testing again from master. The rules/assumptions from the [latest read the docs](http://osquery.readthedocs.org/en/latest/deployment/file-integrity-monitoring/) build should apply.

So if you want to monitor for new files/directories within `/Users` use either `/Users/%` or `/Users/`. 

~~`/Users/%/`~~ will not work because adding a final slash will start monitoring for changes within the existing folders as it causes a wildcard/globbing expansion. So that will not pick up new folders within `/Users/`. ~~`/Users`~~ is also wrong, it's a bit inconvenient but a missing final slash tells FSEvents to restrict monitoring to events on the folder itself. 

The original two:
```
"/Users/%/Applications/%",
"/Users/%/Library/LaunchAgents/%"
```

Would monitor for changes to files/directories within 1 level of Applications and LaunchAgents for existing users.

**Comment by tstallings** [comment]
Ok sweet. I'll give it a whirl in the morning. I'm assuming by master, you mean your master, right

**Comment by theopolis** [comment]
Nope, real master. ;) Or use the Jenkins-built unstable package: https://jenkins.osquery.io/userContent/build/darwin/osquery-1.4.7-61-gba28b47.pkg

**Comment by tstallings** [comment]
Looks like it's working as expected. Nicely done! Thank you!

**Comment by theopolis** [comment]
Perfect! Always happy to help!
