### ISSUE TITLE
deploy: flagfile dropped by Windows MSI contains UTF-16 BOM

### ISSUE THREAD

**Issue by muffins** [facebook/osquery#4548]
The osquery flagsfile deployed by default with the MSI is UTF-16, which isn't parseable by osquery currently.

![capture](https://user-images.githubusercontent.com/1328916/41355242-03c0ef04-6eef-11e8-8028-77643e12bb57.PNG)

**Comment by muffins** [comment]
This was addressed in #4559. We still need to find a way to support UTF-16 strings in our backing store.

**Comment by rozinahudda** [comment]
I am facing issues in adding a windows host to kolide. I see no errors but the host is not added. I have tried changing flag file format to UTF-8 and also tried giving flags inline. Its still not working. Can anyone help?
