### ISSUE TITLE
Parse new plist for login items in macOS >= 10.13.1

### ISSUE THREAD

**Issue by ideologysec** [facebook/osquery#5564]
# Feature request

### What new feature do you want?
Parse the new plist where login items are stored, so the startup_items table is not empty in macOS >=10.13.1

### How is this new feature useful?
this will allow for enumeration of login items on Macs (since this is a malware persistence technique).

### How can this be implemented?
Similar to how the com.apple.loginitems.plist is parsed for startup_items currently,

since 10.13.1 login items live here:
~/Library/Application Support/com.apple.backgroundtaskmanagementagent/backgrounditems.btm
(which is a binary plist with some.... interestingly encoded data).

It should be possible to use the CoreFoundation APIs to parse/understand this.

Additional information with further resource links for understanding:
https://objective-see.com/blog/blog_0x31.md.html

**Comment by directionless** [comment]
Mojave is `~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist`

**Comment by ideologysec** [comment]
I'm happy to take a crack at this; the only question I would have is what the current osquery way is for detecting the host OS version at runtime? I haven't found a good example of this, if someone could point me in that direction that would be awesome.

**Comment by directionless** [comment]
Two possible routes...

You could look at what the `os_version` table uses (https://github.com/osquery/osquery/blob/master/osquery/tables/system/darwin/os_version.cpp)

You could try to read all the possible plist files.

**Comment by theopolis** [comment]
> You could try to read all the possible plist files.

Go for this route. Assume the version of the OS does not matter and try to read each known location where login items may be stored. If the file does not exist move on to the next.

**Comment by mbhatt1** [comment]
Wondering if there is any luck here?

**Comment by theopolis** [comment]
Ping @ideologysec

**Comment by ideologysec** [comment]
I haven't had a chance to touch this; I don't work directly with osquery in my day to day anymore, so this would be a hobby. Thanks for the reminder, I can pick it up and take a look, but can't promise a timeline.

**Comment by Cyb3r-Monk** [comment]
Does this issue still exist?

**Comment by ideologysec** [comment]
@Cyb3r-Monk I think this was resolved at some point in the past. I don't know what the current status is regarding background items in Ventura.

**Comment by Cyb3r-Monk** [comment]
I can still see the login items file under `~/Library/Application\ Support/com.apple.backgroundtaskmanagementagent/backgrounditems.btm`, but I don't see my user's login item in the `launchd` table and there isn't any other table I could find.

**Comment by ideologysec** [comment]
https://github.com/objective-see/dumpbtm
